export const TaiKhoan = [
    {
        id: 1,
        taiKhoan: '19509301',
        matKhau: '19509301',
        loaiTaiKhoan: 'sinhvien',
        khoa: '15',
    },
    {
        id: 2,
        taiKhoan: '19509302',
        matKhau: '19509302',
        loaiTaiKhoan: 'sinhvien',
        khoa: '14',
    },
    {
        id: 3,
        taiKhoan: '19509303',
        matKhau: '19509303',
        loaiTaiKhoan: 'sinhvien',
        khoa: '15',
    },
    {
        id: 4,
        taiKhoan: '19000000',
        matKhau: '19000000',
        loaiTaiKhoan: 'giaovien',
        khoa: '',
    },
    {
        id: 5,
        taiKhoan: 'admin',
        matKhau: 'admin',
        loaiTaiKhoan: 'khoa',
        khoa: '',
    },
    {
        id: 7,
        taiKhoan: '19509333',
        matKhau: '19509333',
        loaiTaiKhoan: 'sinhvien',
        khoa: '17',
    },
];
export const Nha = [
    {
        id: 1,
        te: 'A',
    },
];

export const Phong = [
    {
        id: '1',
        tenPhong: 'A1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1.1',
        tenPhong: 'A12.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '2',
        tenPhong: 'H1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'H',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Thực Hành',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '3',
        tenPhong: 'A2.01',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '4',
        tenPhong: 'E3',
        sucChua: '400',
        trangThai: '1',
        tenNha: 'E',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Hội Trường',
            thietBi: [],
        },
    },
    {
        id: '5',
        tenPhong: 'X1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'X',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [],
        },
    },
    {
        id: '6',
        tenPhong: 'V4.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'V',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [],
        },
    },
    {
        id: '7',
        tenPhong: 'B1.04',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'B',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [],
        },
    },
    {
        id: '8',
        tenPhong: 'H8.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'H',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [],
        },
    },
];

export const SinhVien = {
    ThongTinCaNhan: {
        hoTenSV: 'Ngô Hữu Nghị',
        maSV: '19495921',
        ngaySinh: '20/05/2001',
        gioiTinh: 'Nam',
        noiSinh: 'An Giang',
        SDT: '0877104344',
        CMND: {
            soCMND: '352540248',
            ngayCap: new Date(),
            noiCap: 'An Giang',
        },
        danToc: 'Kinh',
        tonGiao: 'Phật Giáo Hòa Hảo',
        hoKhauThuongTru: 'số 252 Tổ 2 Ấp Hiệp Hòa, Xã Hiệp Xương, Huyện Phú Tân, Tỉnh An Giang',
        email: 'nghiaa1ad0@gmai.com',
        ngayVaoDoan: new Date(),
    },
    ThongTinHocVan: {
        trangThai: 'Đang Học',
        maHoSo: '19NV11697008',
        nienKhoa: '2019-2023',
        ngayVaoTruong: '12/08/2019',
        lopDanhNghia: 'DHKTPM15B',
        bacDaoTao: 'Đại Học',
        loaiHinhDaoTao: 'Chính quy',
        Khoa: 'Công nghệ thông tin',
        chuyenNganh: 'Kỹ thuật phần mềm',
    },
    ThongTinHocPhan: {
        dataSource: [
            { key: '1', monHoc: 'Lập trình phân tán', soTC: '3', soTiet: '45' },
            { key: '2', monHoc: 'Lập trình WWW', soTC: '4', soTiet: '60' },
            { key: '3', monHoc: 'Lập trình Hướng đối tượng', soTC: '4', soTiet: '60' },
            { key: '4', monHoc: 'Kiểm thử phần mềm', soTC: '3', soTiet: '45' },
            { key: '5', monHoc: 'Kiến trúc thiết kế phần mềm', soTC: '4', soTiet: '60' },
            { key: '6', monHoc: 'Mạng máy tính', soTC: '3', soTiet: '45' },
            { key: '7', monHoc: 'An toàn thông tin', soTC: '3', soTiet: '45' },
        ],
        columns: [
            { title: 'Môn học/học phần', dataIndex: 'tenMonHoc', key: 'tenMonHoc' },
            { title: 'Số tín chỉ', dataIndex: 'soTinChi', key: 'soTinChi' },
            { title: 'Số tiết', dataIndex: 'soBuoiHoc', key: 'soBuoiHoc' },
        ],
        appointments: [
            {
                title: 'Lập trình phân tán',
                startDate: new Date(2023, 9, 23, 6, 30),
                endDate: new Date(2023, 9, 23, 9, 0),
                phongHoc: 'X10.06',
                ghiChu: 'Kiem Tra TK1',
                tenGV: 'Châu Thị Bảo Hà',
            },
            {
                title: 'Kiến trúc thiết kế phần mềm',
                startDate: new Date(2023, 9, 23, 9, 10),
                endDate: new Date(2023, 9, 23, 11, 40),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
            {
                title: 'Kiến trúc thiết kế phần mềm',
                startDate: new Date(2023, 9, 24, 12, 30),
                endDate: new Date(2023, 9, 24, 15, 0),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
            {
                title: 'Lập trình phân tán',
                startDate: new Date(2023, 9, 25, 6, 30),
                endDate: new Date(2023, 9, 25, 9, 0),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
            {
                title: 'Kiểm thử phần mềm',
                startDate: new Date(2023, 9, 26, 12, 30),
                endDate: new Date(2023, 9, 26, 15, 0),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
            {
                title: 'An toàn thông tin',
                startDate: new Date(2023, 9, 27, 6, 30),
                endDate: new Date(2023, 9, 27, 9, 0),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
            {
                title: 'Kiến trúc thiết kế phần mềm',
                startDate: new Date(2023, 9, 27, 9, 10),
                endDate: new Date(2023, 9, 27, 11, 40),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
            {
                title: 'Lập trình Hướng đối tượng',
                startDate: new Date(2023, 9, 27, 15, 10),
                endDate: new Date(2023, 9, 27, 17, 40),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
            {
                title: 'Lập trình phân tán',
                startDate: new Date(2023, 9, 28, 9, 10),
                endDate: new Date(2023, 9, 28, 11, 40),
                phongHoc: 'X10.06',
                tenGV: 'Châu Thị Bảo Hà',
                ghiChu: 'không',
            },
        ],
    },
};

export const GiaoVien = {
    ThongTinCaNhan: {
        hoTenGV: 'Nguyễn văn A',
        gioiTinh: 'Nam',
        chucVu: 'Giáo viên thỉnh giảng',
        Khoa: 'Công nghệ thông tin',
        email: 'abc@gmail.com',
        SDT: '0421932109',
    },
    ThongTinGiangDay: {
        lichDay: [],
    },
};


export const MonHoc = {
    data: {
        roomData: [
            {
                maLopHocPhan: '19320812',
                tenMonHoc: 'Lập trình phân tán',
                soTinChi: '3',
                soTietLT: 40,
                soTietTH: 20,
                soBuoiHoc: 20,
                tenNhomThucHanh: 'Nhóm 1',
                trangThai: 'Đã mở lớp',
                thongTinLich: [
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 23, 6, 30),
                        endDate: new Date(2023, 9, 23, 9, 0),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '1-3',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 23, 9, 10),
                        endDate: new Date(2023, 9, 23, 11, 40),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '4-6',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 24, 12, 30),
                        endDate: new Date(2023, 9, 24, 15, 0),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '7-9',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 25, 6, 30),
                        endDate: new Date(2023, 9, 25, 9, 0),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '1-3',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 26, 12, 30),
                        endDate: new Date(2023, 9, 26, 15, 0),
                        phongHoc: 'A10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '7-9',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 27, 6, 30),
                        endDate: new Date(2023, 9, 27, 9, 0),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '1-3',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 27, 9, 10),
                        endDate: new Date(2023, 9, 27, 11, 40),
                        phongHoc: 'A1.03',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '4-6',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 27, 15, 10),
                        endDate: new Date(2023, 9, 27, 17, 40),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '10-12',
                    },
                    {
                        title: 'Lập trình phân tán',
                        startDate: new Date(2023, 9, 28, 9, 10),
                        endDate: new Date(2023, 9, 28, 11, 40),
                        phongHoc: 'A1.03',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '4-6',
                    },
                ],
            },
            {
                maLopHocPhan: '19509301',
                tenMonHoc: 'Lập trình hướng đối tượng',
                soTinChi: '3',
                soTietLT: 40,
                soTietTH: 20,
                soBuoiHoc: 20,
                tenNhomThucHanh: 'Nhóm 1',
                trangThai: 'Đã mở lớp',
                thongTinLich: [
                    {
                        title: 'Lập trình hướng đối tượng',
                        startDate: new Date(2023, 9, 23, 6, 30),
                        endDate: new Date(2023, 9, 23, 9, 0),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '1-3',
                    },
                ],
            },
            {
                maLopHocPhan: '19509300',
                tenMonHoc: 'An toàn thông tin',
                soTinChi: '3',
                soTietLT: 40,
                soTietTH: 20,
                soBuoiHoc: 20,
                tenNhomThucHanh: 'Nhóm 1',
                trangThai: 'Đã mở lớp',
                thongTinLich: [
                    {
                        title: 'An toàn thông tin',
                        startDate: new Date(2023, 9, 23, 6, 30),
                        endDate: new Date(2023, 9, 23, 9, 0),
                        phongHoc: 'X10.06',
                        ghiChu: 'Kiem Tra TK1',
                        tenGV: 'Châu Thị Bảo Hà',
                        tietHoc: '1-3',
                    },
                ],
            },
            {
                maLopHocPhan: '195093010',
                tenMonHoc: 'An toàn thông tin a',
                soTinChi: '3',
                soTietLT: 40,
                soTietTH: 20,
                soBuoiHoc: 20,
                tenNhomThucHanh: 'Nhóm 1',
                trangThai: 'Đã mở lớp',
                thongTinLich: [{}],
            },
            {
                maLopHocPhan: '19509303',
                tenMonHoc: 'An toàn thông tin a1',
                soTinChi: '3',
                soTietLT: 40,
                soTietTH: 20,
                soBuoiHoc: 20,
                tenNhomThucHanh: 'Nhóm 1',
                trangThai: 'Đã mở lớp',
                thongTinLich: [{}],
            },
        ],
    },
};
