export const appointments = [
    {
        title: 'Lập trình phân tán',
        startDate: new Date(2023, 9, 23, 6, 30),
        endDate: new Date(2023, 9, 23, 9, 10),
        phongHoc: 'X10.06',
        ghiChu: 'Kiem Tra TK1',
        tenGV: 'Châu Thị Bảo Hà',
    },
    {
        title: 'Kiến trúc thiết kế phần mềm',
        startDate: new Date(2023, 9, 23, 9, 10),
        endDate: new Date(2023, 9, 23, 11, 40),
        phongHoc: 'X10.06',
        tenGV: 'Châu Thị Bảo Hà',
        ghiChu: 'không',
    },
    {
        title: 'Kiến trúc thiết kế phần mềm',
        startDate: new Date(2023, 9, 24, 12, 30),
        endDate: new Date(2023, 9, 24, 15, 10),
        phongHoc: 'X10.06',
        tenGV: 'Châu Thị Bảo Hà',
        ghiChu: 'không',
    },
    {
        title: 'Lập trình phân tán',
        startDate: new Date(2023, 9, 23, 6, 30),
        endDate: new Date(2023, 9, 23, 9, 10),
        phongHoc: 'X10.06',
        ghiChu: 'Kiem Tra TK1',
        tenGV: 'Châu Thị Bảo Hà',
    },
    {
        title: 'Kiến trúc thiết kế phần mềm',
        startDate: new Date(2023, 9, 23, 9, 10),
        endDate: new Date(2023, 9, 23, 11, 40),
        phongHoc: 'X10.06',
        tenGV: 'Châu Thị Bảo Hà',
        ghiChu: 'không',
    },
    {
        title: 'Kiến trúc thiết kế phần mềm',
        startDate: new Date(2023, 9, 24, 12, 30),
        endDate: new Date(2023, 9, 24, 15, 10),
        phongHoc: 'X10.06',
        tenGV: 'Châu Thị Bảo Hà',
        ghiChu: 'không',
    }
]


export const Phong = [
    {
        id: '1',
        tenPhong: 'A1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1.1',
        tenPhong: 'A12.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1',
        tenPhong: 'A1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1.1',
        tenPhong: 'A12.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1',
        tenPhong: 'A1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1.1',
        tenPhong: 'A12.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1',
        tenPhong: 'A1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1.1',
        tenPhong: 'A12.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1',
        tenPhong: 'A1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1.1',
        tenPhong: 'A12.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1',
        tenPhong: 'A1.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    },
    {
        id: '1.1',
        tenPhong: 'A12.03',
        sucChua: '50',
        trangThai: '1',
        tenNha: 'A',
        loaiPhong: {
            id: 'loai1',
            tenLoai: 'Phòng Lý Thuyết',
            thietBi: [
                {
                    id: 'tb1',
                    tenThietBi: 'Máy chiếu',
                    loai: 'may-chieu',
                    ngayMua: new Date('2023-08-20'),
                    nhaCungCap: 'LG ĐN',
                },
                {
                    id: 'tb2',
                    tenThietBi: 'Màn trắng',
                    loai: 'man-trang',
                    ngayMua: new Date('2023-05-20'),
                    nhaCungCap: 'LG ĐN',
                },
            ],
        },
    }]